---
title: "R Notebook"
output: html_notebook
---

```{r}
devtools::load_all("~/ACTIONet/")
source("functions.R")

```

```{r}
aces = readr::read_rds("ACTIONet/all_in_one_filtered.rds")
all.markers = readr::read_rds("markers.rds")

```


```{r}
require(ACTIONet)
method = "ACTIONet"

perf = list()
scores = list()
labels = list()

for(i in 1:length(aces)) {
  dataset = names(aces)[[i]]
  print(dataset)

  ace = aces[[i]]
  markers = all.markers[[i]]
  true_labels = ace$Labels
  
  mm = ACTIONet:::.preprocess_annotation_markers(lapply(markers, toupper), rownames(ace))
  markers = apply(mm, 2, function(x) toupper(rownames(mm)[x > 0]))
  mm = ACTIONet:::.preprocess_annotation_markers(lapply(markers, toupper), rownames(ace))
  
  
  G = ace$ACTIONet
  S = logcounts(ace)
  cell.scores = compute_marker_aggregate_stats_TFIDF_sum_smoothed(G, S, mm, alpha = 0.99, thread_no = 42, normalization = 0)
  Labels = factor(colnames(mm)[apply(cell.scores, 1, which.max)], colnames(mm))
  colnames(cell.scores) = colnames(mm)
  
  labels[[dataset]] = Labels
  scores[[dataset]] = cell.scores

  perf[[dataset]] = assess.annotation(ace, labels = labels[[dataset]], true_labels = true_labels, scores = scores[[dataset]], exp_name = paste(dataset, method, sep = "_"))
}
perfs = do.call(rbind, perf)
readr::write_rds(perfs, "~/results/ACTIONet_new_deep_noTFIDF_perfs.rds")
readr::write_rds(scores, "~/results/ACTIONet_new_deep_noTFIDF_scores.rds")
readr::write_rds(labels, "~/results/ACTIONet_new_deep_noTFIDF_labels.rds")

```

